:lbl_pesquisar_id	ID
:lbl_pesquisar_status	Status
:tc_pesquisar_status	unset
:lbl_pesquisar_usage	Usage
:tc_pesquisar_usage	unset
:lbl_pesquisar_number	Number
:label_item_05	Status
:tc_editor_status	unset
:label_item_06	Date Installed
:label_item_07	Usage
:tc_editor_usage	unset
:label_item_08	Material
:tc_editor_material	unset
:label_item_09	Number
:label_item_10	Strength
:tc_editor_strength	unset
:label_item_14	Owner Type
:tc_editor_owner_type	unset
:label_item_13	Treatment
:tc_editor_treatment	unset
:label_item_11	Owner Name
:tc_editor_owner_name	unset
:label_item_12	ID
:quit	Quit
:about	About









